# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
[:admin, :field_manager, :field_staff].each do |role|
  Role.find_or_create_by_name({ name: role })
User.new({:first_name => "system", :last_name => "admin", :email => "test_admin@example.com", :approved => 1, :password => "wisc_admin", :password_confirmation => "wisc_admin" }).save(:validate => false)

Classification.create({:class_id => "1", :class_name => "Urban Developed"})
Classification.create({:class_id => "2", :class_name => "Agriculture"})
Classification.create({:class_id => "3", :class_name => "Forest"})
Classification.create({:class_id => "4", :class_name => "Shrubland"})
Classification.create({:class_id => "5", :class_name => "Grassland"})
Classification.create({:class_id => "6", :class_name => "Open Water"})
Classification.create({:class_id => "7", :class_name => "Barren"})
Classification.create({:class_id => "8", :class_name => "Wetland"})

Classification.create({:class_id => "11", :class_name => "High Intensity Urban"})
Classification.create({:class_id => "12", :class_name => "Low Intensity Urban"})
Classification.create({:class_id => "21", :class_name => "Row Crops"})
Classification.create({:class_id => "22", :class_name => "Forage Crops"})
Classification.create({:class_id => "31", :class_name => "Coniferous"})
Classification.create({:class_id => "32", :class_name => "Broad-leaved Deciduous"})
Classification.create({:class_id => "33", :class_name => "Mixed Coniferous/Broad-leaved Deciduous"})
Classification.create({:class_id => "34", :class_name => "Clearcut/Young Plantation"})
Classification.create({:class_id => "41", :class_name => "Upland Shrub"})
Classification.create({:class_id => "51", :class_name => "Grassland"})
Classification.create({:class_id => "61", :class_name => "Open Water"})
Classification.create({:class_id => "71", :class_name => "Sand"})
Classification.create({:class_id => "72", :class_name => "Bare Soil"})
Classification.create({:class_id => "73", :class_name => "Exposed Rock"})
Classification.create({:class_id => "74", :class_name => "Mixed"})
Classification.create({:class_id => "81", :class_name => "Emergent/Wet Meadow"})
Classification.create({:class_id => "82", :class_name => "Lowland Shrub"})
Classification.create({:class_id => "83", :class_name => "Broad-leaved Evergreen"})
Classification.create({:class_id => "84", :class_name => "Forested Wetland"})

Classification.create({:class_id => "821", :class_name => "Coniferous"})
Classification.create({:class_id => "822", :class_name => "Broad-leaved Deciduous"})
Classification.create({:class_id => "841", :class_name => "Coniferous"})
Classification.create({:class_id => "842", :class_name => "Broad-leaved Deciduous"})
Classification.create({:class_id => "843", :class_name => "Mixed Coniferous/Broad-leaved Deciduous"})

ForestType.create({:forest_id =>"1",:species_name=>"Alder" })
ForestType.create({:forest_id =>"2",:species_name=>"Almer Elm" })
ForestType.create({:forest_id =>"3",:species_name=>"Aspen" })
ForestType.create({:forest_id =>"4",:species_name=>"Balsam Fir" })
ForestType.create({:forest_id =>"5",:species_name=>"Basswood" })
ForestType.create({:forest_id =>"6",:species_name=>"Beech" })
ForestType.create({:forest_id =>"7",:species_name=>"Black Ash" })
ForestType.create({:forest_id =>"8",:species_name=>"Black Cherry" })
ForestType.create({:forest_id =>"9",:species_name=>"Black Spruce" })
ForestType.create({:forest_id =>"10",:species_name=>"Black Willow" })
ForestType.create({:forest_id =>"11",:species_name=>"Cottonwood" })
ForestType.create({:forest_id =>"12",:species_name=>"Green Ash" })
ForestType.create({:forest_id =>"13",:species_name=>"Hemlock" })
ForestType.create({:forest_id =>"14",:species_name=>"Jack Pine" })
ForestType.create({:forest_id =>"15",:species_name=>"N. Pin Oak" })
ForestType.create({:forest_id =>"16",:species_name=>"Red Maple" })
ForestType.create({:forest_id =>"17",:species_name=>"Red Pine" })
ForestType.create({:forest_id =>"18",:species_name=>"Red/Black Oak" })
ForestType.create({:forest_id =>"19",:species_name=>"River Birch" })
ForestType.create({:forest_id =>"20",:species_name=>"Silver Maple" })
ForestType.create({:forest_id =>"21",:species_name=>"Slippery Elm" })
ForestType.create({:forest_id =>"22",:species_name=>"Sugar Maple" })
ForestType.create({:forest_id =>"23",:species_name=>"Tamarack" })
ForestType.create({:forest_id =>"24",:species_name=>"White Birch" })
ForestType.create({:forest_id =>"25",:species_name=>"White Cedar" })
ForestType.create({:forest_id =>"26",:species_name=>"White Pine" })
ForestType.create({:forest_id =>"27",:species_name=>"White Spruce" })
ForestType.create({:forest_id =>"28",:species_name=>"White/Bur Oak" })
ForestType.create({:forest_id =>"29",:species_name=>"Yellow Birch" })

Vegetation.create({:vegetation_id =>"1",:vegetation_name=>"Small Tree" })
Vegetation.create({:vegetation_id =>"2",:vegetation_name=>"Vegetation" })
Vegetation.create({:vegetation_id =>"3",:vegetation_name=>"Sapling" })
Vegetation.create({:vegetation_id =>"4",:vegetation_name=>"Herbaceous Vegetation" })

end